export const AJUSTE_CREATE_REQUEST = "AJUSTE_CREATE_REQUEST";
export const AJUSTE_CREATE_SUCCESS = "AJUSTE_CREATE_SUCCESS";
export const AJUSTE_CREATE_FAIL = "AJUSTE_CREATE_FAIL";
export const AJUSTE_CREATE_RESET = "AJUSTE_CREATE_RESET";

export const AJUSTE_DETAILS_REQUEST = "AJUSTE_DETAILS_REQUEST";
export const AJUSTE_DETAILS_SUCCESS = "AJUSTE_DETAILS_SUCCESS";
export const AJUSTE_DETAILS_FAIL = "AJUSTE_DETAILS_FAIL";

export const AJUSTE_LIST_REQUEST = "AJUSTE_LIST_REQUEST";
export const AJUSTE_LIST_SUCCESS = "AJUSTE_LIST_SUCCESS";
export const AJUSTE_LIST_FAIL = "AJUSTE_LIST_FAIL";
