export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL";
export const ORDER_DELETE_RESET = "ORDER_DELETE_RESET";

export const ORDER_SUMMARY_REQUEST = "ORDER_SUMMARY_REQUEST";
export const ORDER_SUMMARY_SUCCESS = "ORDER_SUMMARY_SUCCESS";
export const ORDER_SUMMARY_FAIL = "ORDER_SUMMARY_FAIL";

export const ORDER_ALL_REQUEST = "ORDER_ALL_REQUEST";
export const ORDER_ALL_SUCCESS = "ORDER_ALL_SUCCESS";
export const ORDER_ALL_FAIL = "ORDER_ALL_FAIL";

export const GROUPBYDAY_REQUEST = "GROUPBYDAY_REQUEST";
export const GROUPBYDAY_SUCCESS = "GROUPBYDAY_SUCCESS";
export const GROUPBYDAY_FAIL = "GROUPBYDAY_FAIL";
export const GROUPBYDAY_RESET = "GROUPBYDAY_RESET";

export const CUADREDIA_REQUEST = "CUADREDIA_REQUEST";
export const CUADREDIA_SUCCESS = "CUADREDIA_SUCCESS";
export const CUADREDIA_FAIL = "CUADREDIA_FAIL";
export const CUADREDIA_RESET = "CUADREDIA_RESET";

export const ORDER_WEEKLY_REQUEST = "ORDER_WEEKLY_REQUEST";
export const ORDER_WEEKLY_SUCCESS = "ORDER_WEEKLY_SUCCESS";
export const ORDER_WEEKLY_FAIL = "ORDER_WEEKLY_FAIL";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_CONSOLIDADO_REQUEST = "ORDER_CONSOLIDADO_REQUEST";
export const ORDER_CONSOLIDADO_SUCCESS = "ORDER_CONSOLIDADO_SUCCESS";
export const ORDER_CONSOLIDADO_FAIL = "ORDER_CONSOLIDADO_FAIL";

export const ARTICULO_CONSOLIDADO_REQUEST = "ARTICULO_CONSOLIDADO_REQUEST";
export const ARTICULO_CONSOLIDADO_SUCCESS = "ARTICULO_CONSOLIDADO_SUCCESS";
export const ARTICULO_CONSOLIDADO_FAIL = "ARTICULO_CONSOLIDADO_FAIL";
