
export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_LIST_RESET = "PRODUCT_LIST_RESET";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_ALL_REQUEST = "PRODUCT_ALL_REQUEST";
export const PRODUCT_ALL_SUCCESS = "PRODUCT_ALL_SUCCESS";
export const PRODUCT_ALL_FAIL = "PRODUCT_ALL_FAIL";

export const PRODUCT_CONTEO_RAPIDO_REQUEST = "PRODUCT_CONTEO_RAPIDO_REQUEST";
export const PRODUCT_CONTEO_RAPIDO_SUCCESS = "PRODUCT_CONTEO_RAPIDO_SUCCESS";
export const PRODUCT_CONTEO_RAPIDO_FAIL = "PRODUCT_CONTEO_RAPIDO_FAIL";
export const PRODUCT_CONTEO_RAPIDO_RESET = "PRODUCT_CONTEO_RAPIDO_RESET";

export const PRODUCT_CARGARSTOCK_REQUEST = "PRODUCT_CARGASTOCK_REQUEST";
export const PRODUCT_CARGARSTOCK_SUCCESS = "PRODUCT_CARGASTOCK_SUCCESS";
export const PRODUCT_CARGARSTOCK_FAIL = "PRODUCT_CARGASTOCK_FAIL";
export const PRODUCT_CARGARSTOCK_RESET = "PRODUCT_CARCGASTOCK_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const PRODUCT_SEARCH_REQUEST = "PRODUCT_SEARCH_REQUEST";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
export const PRODUCT_SEARCH_FAIL = "PRODUCT_SEARCH_FAIL";
export const PRODUCT_SEARCH_RESET = "PRODUCT_SEARCH_RESET";


export const PRODUCT_CARGARSTOCKCHACAO_REQUEST =
    "PRODUCT_CARGASTOCKCHACAO_REQUEST";
export const PRODUCT_CARGARSTOCKCHACAO_SUCCESS =
    "PRODUCT_CARGASTOCKCHACAO_SUCCESS";
export const PRODUCT_CARGARSTOCKCHACAO_FAIL = "PRODUCT_CARGASTOCKCHACAO_FAIL";
export const PRODUCT_CARGARSTOCKCHACAO_RESET =
    "PRODUCT_CARCGASTOCKCHACAO_RESET";

