export const REPOSICION_CREATE_REQUEST = "REPOSICION_CREATE_REQUEST";
export const REPOSICION_CREATE_SUCCESS = "REPOSICION_CREATE_SUCCESS";
export const REPOSICION_CREATE_FAIL = "REPOSICION_CREATE_FAIL";
export const REPOSICION_CREATE_RESET = "REPOSICION_CREATE_RESET";

export const REPOSICION_DETAILS_REQUEST = "REPOSICION_DETAILS_REQUEST";
export const REPOSICION_DETAILS_SUCCESS = "REPOSICION_DETAILS_SUCCESS";
export const REPOSICION_DETAILS_FAIL = "REPOSICION_DETAILS_FAIL";

export const REPOSICION_LIST_REQUEST = "REPOSICION_LIST_REQUEST";
export const REPOSICION_LIST_SUCCESS = "REPOSICION_LIST_SUCCESS";
export const REPOSICION_LIST_FAIL = "REPOSICION_LIST_FAIL";

export const REPOSICION_DELETE_REQUEST = "REPOSICION_DELETE_REQUEST";
export const REPOSICION_DELETE_SUCCESS = "REPOSICION_DELETE_SUCCESS";
export const REPOSICION_DELETE_FAIL = "REPOSICION_DELETE_FAIL";
export const REPOSICION_DELETE_RESET = "REPOSICION_DELETE_RESET";

export const REPOSICION_UPDATE_STATUS_REQUEST =
  "REPOSICION_UPDATE_STATUS_REQUEST";
export const REPOSICION_UPDATE_STATUS_SUCCESS =
  "REPOSICION_UPDATE_STATUS_SUCCESS";
export const REPOSICION_UPDATE_STATUS_FAIL = "REPOSICION_UPDATE_STATUS_FAIL";
export const REPOSICION_UPDATE_STATUS_RESET = "REPOSICION_UPDATE_STATUS_RESET";
